-- Spring Session JDBC 스키마 — PostgreSQL 전용 DDL
-- 출처: spring-session/spring-session-jdbc/src/main/resources/org/springframework/session/jdbc/schema-postgresql.sql

-- ============================================================
-- SPRING_SESSION
-- ============================================================
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            CHAR(36)     NOT NULL,
    SESSION_ID            CHAR(36)     NOT NULL,
    CREATION_TIME         BIGINT       NOT NULL,
    LAST_ACCESS_TIME      BIGINT       NOT NULL,
    MAX_INACTIVE_INTERVAL INT          NOT NULL,
    EXPIRY_TIME           BIGINT       NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100) DEFAULT NULL,

    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

COMMENT ON TABLE  SPRING_SESSION                    IS 'Spring Session JDBC — HTTP 세션 메타데이터';
COMMENT ON COLUMN SPRING_SESSION.PRIMARY_ID         IS '내부 기본키 UUID (PK)';
COMMENT ON COLUMN SPRING_SESSION.SESSION_ID         IS '클라이언트 세션 쿠키 값 (UNIQUE)';
COMMENT ON COLUMN SPRING_SESSION.CREATION_TIME      IS '세션 생성 시각 (epoch millis)';
COMMENT ON COLUMN SPRING_SESSION.LAST_ACCESS_TIME   IS '마지막 접근 시각 (epoch millis)';
COMMENT ON COLUMN SPRING_SESSION.MAX_INACTIVE_INTERVAL IS '비활성 만료 간격 (초)';
COMMENT ON COLUMN SPRING_SESSION.EXPIRY_TIME        IS '만료 시각 (epoch millis, cleanup 쿼리용)';
COMMENT ON COLUMN SPRING_SESSION.PRINCIPAL_NAME     IS '인증 주체 이름 (전체 로그아웃 쿼리용)';

-- ============================================================
-- SPRING_SESSION_ATTRIBUTES
-- ============================================================
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BYTEA        NOT NULL,

    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK
        PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK
        FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  SPRING_SESSION_ATTRIBUTES                        IS 'Spring Session JDBC — 세션 attribute (SecurityContext 등)';
COMMENT ON COLUMN SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID     IS '세션 FK (SPRING_SESSION.PRIMARY_ID, CASCADE DELETE)';
COMMENT ON COLUMN SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME         IS 'attribute 키 이름 (복합 PK)';
COMMENT ON COLUMN SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES        IS '직렬화된 attribute 값 (BYTEA)';
